repos:
  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-json
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: detect-private-key
      - id: mixed-line-ending

  # Ruff - Fast Python linter and formatter (replaces black, isort, flake8, bandit)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix]
      # Run the formatter
      - id: ruff-format

  # Type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        args: ['--ignore-missing-imports', '--warn-unused-configs']
        additional_dependencies: [types-PyYAML, types-requests]
        exclude: '^tests/'

  # Markdown formatting
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
          - mdformat-frontmatter
        args: ['--wrap', '100']

  # Secret detection
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: |
          (?x)^(
            \.archive/.*|
            \.codex_temp/.*|
            \.codex_tmp/.*|
            outputs/.*|
            demo/evidence/.*|
            \.git/.*
          )$

  # Run tests on commit
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: bash -c 'pytest tests/unit -v --tb=short -x || (echo "❌ Unit tests failed. Fix tests before committing." && exit 1)'
        language: system
        pass_filenames: false
        always_run: false
        stages: [pre-push]
